# Generated by Django 6.0.4 on 2026-04-15 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.JSONField(default=list)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('category', models.CharField(choices=[('biology', 'Biology'), ('chemistry', 'Chemistry'), ('math', 'Math')], default='biology', max_length=50)),
                ('external_mentor', models.CharField(max_length=255)),
                ('secondary_director', models.CharField(max_length=255)),
                ('external_mentor_institute', models.CharField(max_length=255)),
                ('room_number', models.CharField(max_length=50)),
                ('cross_linked_labs', models.ManyToManyField(blank=True, related_name='linked_presentations', to='lookup.presentation')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lookup.timeslot')),
            ],
        ),
    ]
