# Generated by Django 6.0.4 on 2026-04-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='category',
            field=models.CharField(choices=[('astro', 'Astronomy and Astrophysics'), ('bio', 'Biotechnology and Life Sciences'), ('chem', 'Chemical Analysis and Nanochemistry'), ('cs', 'Computer Systems'), ('eng', 'Engineering'), ('mbw', 'Mobile and Web Application Development'), ('neuro', 'Neuroscience'), ('ocean', 'Oceanography and Geophysical Systems'), ('qlab', 'Quantum Physics and Optics')], max_length=50),
        ),
    ]
