# Generated by Django 6.0.4 on 2026-04-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_alter_presentation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='external_mentor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='external_mentor_institute',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='secondary_director',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
