# Generated by Django 6.0.4 on 2026-05-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_alter_presentation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='primary_director',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='presentation',
            name='secondary_lab',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
