# Generated by Django 6.0.4 on 2026-05-03 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0005_presentation_primary_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2026, 5, 3, 13, 38, 15, 504864, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2026, 5, 3, 13, 38, 26, 532243, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
