# Generated by Django 6.0.4 on 2026-05-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0006_presentation_end_time_presentation_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ['timeslot__block', 'room_number']},
        ),
    ]
