# Generated by Django 6.0.4 on 2026-05-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0007_alter_presentation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='presentation',
            name='primary_director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lookup.labdirector'),
        ),
    ]
