# Generated by Django 6.0.4 on 2026-05-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0008_labdirector_alter_presentation_primary_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labdirector',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='labdirector',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'title'), name='unique_labdirector_identity'),
        ),
    ]
