[project]
name = "tjstar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dj-database-url>=3.1.2",
    "django>=6.0.4",
    "faker>=40.13.0",
    "gunicorn>=25.3.0",
    "psycopg>=3.3.3",
    "python-dotenv>=1.2.2",
    "social-auth-app-django>=5.7.0",
    "whitenoise>=6.12.0",
]
